### ISSUE TITLE
Add account snapshots

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/ousd-analytics#205]
Add account snapshots so we can get token and ETH balances.  Then we can build some notification triggers for things we're interested int.  e.g. low OGN balance on a specific address.

**Comment by joshfraser** [comment]
Specifically we care about monitoring the team & investor T3 hot wallets.

**Comment by joshfraser** [comment]
Master Linton solved this already

**Comment by mikeshultz** [comment]
> Master Linton solved this already

I'm always in awe of that man's speed.  

Was it added to T3?  Might we still want it as part of this for other reasons, like relevant accounts to watch or keeping a historical record?
