### ISSUE TITLE
Add stablecoin market share to analytics

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd-analytics#216]
Let's add a chart depicting OUSD's market cap as a percentage of the entire stablecoin market. I don't think we need lines for every stablecoin to start with, we can just have a single line that is OUSD's percentage. For the purposes of calculating the aggregate market cap (denominator), let's sum the market cap of the top 50 stablecoins according to [DeFi Llama](https://defillama.com/stablecoins).

**Comment by rolandpo** [comment]
I think doing this on Dune would only allow me to compare OUSD's market cap to the general stablecoin market cap on Ethereum. Otherwise we would need some other way of visualising this

**Comment by micahalcorn** [comment]
> I think doing this on Dune would only allow me to compare OUSD's market cap to the general stablecoin market cap on Ethereum. Otherwise we would need some other way of visualising this

That sounds fine. How is the general stablecoin market cap on Dune calculated or defined? Can you point to an example?

**Comment by rolandpo** [comment]
here's a cool dashboard: https://dune.com/hagaetc/stablecoins, they have a stablecoin abstraction that looks like it's just subtracting burns from mints for the top 26 tokens (no OUSD tho)

**Comment by micahalcorn** [comment]
> here's a cool dashboard: https://dune.com/hagaetc/stablecoins, they have a stablecoin abstraction that looks like it's just subtracting burns from mints for the top 26 tokens (no OUSD tho)

That looks like a reasonable source. We could start with those 20 and then add more later?

**Comment by rolandpo** [comment]
sounds good
