### ISSUE TITLE
Add monitoring for the new governance and timelock contracts

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/ousd-analytics#221]
Soon we'll be transferring ownership of the OUSD protocol to the governance contracts
See https://github.com/OriginProtocol/ousd-governance/pull/332

1. We should update our monitoring so that all events issued by those contracts get captured and generate notifications to our discord `ousd-bot` channel.
2. The governance events should show in the analytics "Recent Activity" UI. See bottom of the page at https://analytics.ousd.com/

**Comment by franckc** [comment]
Hi @ivanzhelyazkov ,
We are planning on switching over to the new governance system soon so checking in on this issue since it will be important to have this in.
Any chance you could finish this before leaving for Devcon?
thank you... :)

**Comment by ivanzhelyazkov** [comment]
Hey Franck, I actually have a PR up for this #223 since Monday, waiting to be reviewed.

**Comment by franckc** [comment]
This is deployed to prod. Nice work @ivanzhelyazkov !
