### ISSUE TITLE
Strategies monitoring: 3Crv balance

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd-analytics#236]
Alert ourselves in Discord, Email, and SMS if the 3Crv portion of a given Curve metapool falls below a certain threshold when we have funds allocated to it.

**Comment by shahthepro** [comment]
This is done as part of the PR #252, though it's not yet merged or deployed (Have to clean up a few things as part of Heroku migration)

**Comment by franckc** [comment]
I think we should implement this on the new Prometheus based monitoring/alerting system rather than on the old analytics stack.
Do you agree @sparrowDom @shahthepro ?

**Comment by sparrowDom** [comment]
thanks @franckc yes completely agree. We already monitor 3pool via prometheus/Grafana and any time will have email + sms alerts setup. 

Closing this ticket since the functionality will be present as part of this ticket: https://github.com/OriginProtocol/origin-dollar/issues/1231
