### ISSUE TITLE
Suppress mint Transfer events

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/ousd-analytics#25]
We can probably suppress Transfer events that occur during mints as they're confusing.  Can probably suppress any where `from` is a zero-address.

![mint_transfer](https://user-images.githubusercontent.com/1048089/103790812-eb209280-4ffe-11eb-9a4f-78242ddc4851.png)

**Comment by DanielVF** [comment]
Go for it!

**Comment by franckc** [comment]
Just to clarify: are we thinking a contract change or an analytics change?

**Comment by DanielVF** [comment]
Analytics.
