### ISSUE TITLE
Incorrect OUSD Curve metapool position

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd-analytics#287]
Our overall position in the OUSD Curve metapool is being correctly reported (currently 35,059,920). However, the breakdown of that strategy is incorrect. We're currently showing an even split between OUSD and 3Crv, but OUSD makes up 65% of the pool. As a result, our OUSD position in the pool should be 22,785,442 instead of 17,529,960. This inaccuracy causes our new AUM calculation to be incorrect because we only have 12,274,478 DAI/USDC/USDT instead of the reported 17,529,960. The strategy and OUSD as a whole are still just as solvent as expected, but we don't have an accurate picture of our current non-USD holdings.

Ideally, we would have a semi-real-time measurement of both the metapool makeup and 3pool's makeup. The former is more important than the latter in this case, but a solution might solve both at the same time. We'll probably want a generalized solution anyway because we'll want it for other Curve-related strategies that we deploy in the future (e.g. LUSD+3Crv). If we currently have a blockchain listener, it could monitor any fund movements in those pools. Otherwise, we could query the balances on each analytics request (with caching).

<img width="268" alt="Screenshot 2023-02-27 at 12 47 47 PM" src="https://user-images.githubusercontent.com/273937/221682089-53df87fe-0312-4cce-b149-2930187804a2.png">

**Comment by rolandpo** [comment]
done in #290
