### ISSUE TITLE
Percentage staked discrepancy

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd-analytics#294]
The **Percentage staked** (OGV) according to our weekly email report is a bit lower than what is being shown on the token dashboard.

<img width="602" alt="Screenshot 2023-03-05 at 6 59 33 PM" src="https://user-images.githubusercontent.com/273937/223009475-f47ca229-82b2-42e5-b091-94eb3facfea4.png">

<img width="466" alt="Screenshot 2023-03-05 at 7 01 04 PM" src="https://user-images.githubusercontent.com/273937/223009651-f976caea-5bcc-4dc5-a4d7-284f2e38236f.png">

**Comment by rolandpo** [comment]
fixed in https://github.com/OriginProtocol/ousd.com/pull/99 on frontend side
