### ISSUE TITLE
Sticky email recipient

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd-analytics#295]
One of the recipients of our weekly analytics report email is our core team email list. We use this because it ensures that the email gets delivered to everyone on the team regardless of who comes and goes. This saves us from needing to remember to add and remove people as the team evolves.

Last week, someone on the team inadvertently unsubscribed us from the list. Let's find a way to prevent that in the future. My recommendation would be to store this email address in an environment variable and then append it to the subscriber list each time the email is sent. That would allow us to avoid advertising the email address in our open-source code. We previoualy used and environment variable for the entire list (comma-separated), but I don't think there's any need for that right now since we have moved the list to the db.

**Comment by rolandpo** [comment]
done in #298
