### ISSUE TITLE
Repair syncing to Metabase

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd-analytics#296]
I'm looking for the weekly analytics report subscribers table and I can't find it.

<img width="544" alt="Screenshot 2023-03-07 at 6 02 39 AM" src="https://user-images.githubusercontent.com/273937/223444847-207a564a-aad8-45a9-929c-215c217b461b.png">
<img width="906" alt="Screenshot 2023-03-07 at 7 19 31 AM" src="https://user-images.githubusercontent.com/273937/223465910-49ab8e47-a8e1-49cc-a2b4-04eb865780a4.png">

**Comment by franckc** [comment]
@jonathansnow Could you help with that?

**Comment by shahthepro** [comment]
Adding context to this, it is probably because of the migration. The database is now on Heroku. And the one on GCP is already deleted

**Comment by jonathansnow** [comment]
I will take a look at this today, we will just need to create Metabase credentials for the database on Heroku and update the connection details in Metabase

**Comment by jonathansnow** [comment]
Created new read-only credentials in Heroku for Metabase and updated the connection details. Looks to be working now.

**Comment by jonathansnow** [comment]
Closing as this is working as expected
