### ISSUE TITLE
Add OETH to analytics report email

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd-analytics#304]
Our weekly and monthly emails include highlights for OUSD and OGV. We'll want to update them to also include OETH. Here are a few observations:

- The logo at the top should probably be changed to **ORIGIN**DeFi, assuming that we're creating that already for Twitter.
- We'll want a new OETH section below the OUSD section (before the OGV section).
- For the OETH version, let's keep the same four top indicators but replace stablecoin market share with LSD market share.
- It probably makes sense to have separate "More details" for OETH rather than combine the fees generated by both products. For the accounts holding more than X, I would go with 0.1 OETH.

**Comment by joshfraser** [comment]
Let's swap the order of the columns while we're at it. Since we read left to right, it makes more sense to put the previous week's stats on the left and the most recent week on the right.

**Comment by micahalcorn** [comment]
In my experience, public company financial reports have the current period followed by historical periods in reverse chronological order but it doesn't matter that much to me either way. Maybe it's the placement of the change column (at the end) that causes it to feel unnatural.

**Comment by micahalcorn** [comment]
> * We'll want a new OETH section below the OUSD section (before the OGV section).

Also, on second thought, let's put the new OETH section at the top ahead of the OUSD section.

**Comment by micahalcorn** [comment]
As suggested by @matt-bullock, it would be helpful to add "Yield generated" above the fees and rename the fees to "Protocol fees earned".

**Comment by matt-bullock** [comment]
Added the updates to the design. I think we can remove the 'More details' separation from each unless you like it?

https://www.figma.com/file/QZnkBcAebaVrUfFLBmapzW/Analytics-Report-Email?node-id=88%3A1163&t=ComwxB35Dl7Kzg4t-1

<img width="492" alt="image" src="https://user-images.githubusercontent.com/39496225/233160019-b6191fd4-d4bf-43cf-8793-4d386d183039.png">

**Comment by micahalcorn** [comment]
@matt-bullock similar to analytics dashboard, well need to decide whether to show these OETH stats in USD denomination or ETH or OETH.

**Comment by micahalcorn** [comment]
> @matt-bullock similar to analytics dashboard, well need to decide whether to show these OETH stats in USD denomination or ETH or OETH.

Here's an updated mockup with USD-equivalents added:

<img width="924" alt="image" src="https://github.com/OriginProtocol/ousd-analytics/assets/273937/41e02df6-248c-4cd4-99b7-9fd11bd35ce1">

Note that it's missing the split of circulating and protocol-owned. We **do** want that instead of total supply for both OUSD and OETH.

<img width="518" alt="Screenshot 2023-05-22 at 1 32 21 AM" src="https://github.com/OriginProtocol/ousd-analytics/assets/273937/7eb752fe-892c-4fec-a47d-f974980a9b38">

**Comment by matt-bullock** [comment]
Most recent mock:

https://www.figma.com/file/QZnkBcAebaVrUfFLBmapzW/Analytics-Report-Email?type=design&node-id=628%3A1473&t=01XzS8OoMLaANpaD-1

![image](https://github.com/OriginProtocol/ousd-analytics/assets/39496225/e2502736-c4f1-41b9-b1f3-f670ee0a2155)

**Comment by shahthepro** [comment]
This is done. Closing this
