### ISSUE TITLE
OETH analytics

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd-analytics#306]
- [x] TVL(USD)
- [x] Total supply(ETH)
- [x] APY
- [x] Strategy allocation
- [x] Collateral we are holding
- [x] Protocol fees(nice to have)
- [ ] LSD market share(nice to have)

**Backend**
- Update existing backend analytics.ousd.com to listen for OETH contract events + expose data thru new endpoints (will require updating the DB schema)
- Hook up with Discord bot

**Comment by shahthepro** [comment]
Should we close this and create a separate issue for market share?
