### ISSUE TITLE
APY table frozen

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd-analytics#322]
The table at /apy has not updated in ten days.

![apy](https://github.com/OriginProtocol/ousd-analytics/assets/273937/00e300b7-ed85-4b05-b360-83f0d886f00d)

**Comment by shahthepro** [comment]
This is fixed now 
![image](https://github.com/OriginProtocol/ousd-analytics/assets/10547529/90d8b537-99ca-4ba5-a914-8f5f7f00f3d4)
