### ISSUE TITLE
Endpoint for CoinGecko

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd-analytics#44]
We would like to add an API endpoint for CoinGecko to consume for their [farms page](https://www.coingecko.com/yield-farming). According to [their spec](https://docs.google.com/document/d/1v27QFoQq1SKT3Priq3aqPgB70Xd_PnDzbOCiuoCyixw/edit), we need to create an unauthenticated JSON endpoint at /pools that returns the following data:

Name | Data Type
:-- | :--
identifier | string
liquidity_locked | decimal
apy | decimal

We'll want to include OUSD and each of the OGN staking options. Here's an example of what I think the output should look like:

```js
[
  {
    identifier: "OUSD Vault",
    liquidity_locked: 2,439,853.41,
    apy: 110.91
  },
  {
    identifier: "OGN 30-day Staking",
    liquidity_locked: 1054008.28,
    apy: 7.5
  },
  {
    identifier: "OGN 90-day Staking",
    liquidity_locked: 1523147.1,
    apy: 12.5
  },
  {
    identifier: "OGN 365-day Staking",
    liquidity_locked: 3093561.25,
    apy: 25.0
  }
]
```

**Comment by mikeshultz** [comment]
Just use the same 7-day trailing APY for OUSD?

**Comment by mikeshultz** [comment]
PR up.  Used 7-day trailing.  I just used your example rather than reading that massive doc.  Thanks for digesting it for me!
