### ISSUE TITLE
Compound supply threshold change

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/ousd-analytics#51]
To alleviate some notification fatigue, split the Compound trigger into multiple severities and thresholds.  A 5%, which it may be interesting, does not warrant an urgent response. And a 10%, could be rare(don't know yet) but isn't necessarily critical.  Whereas, a 25% movement requires some eyeballs to make sure everything isn't collapsing.

Severity | Threshold
-----------|---------------
Normal  | 5%
High      | 10%
Critical  | 25%

**Comment by DanielVF** [comment]
Makes sense!
