### ISSUE TITLE
Mint Rate > 1

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd-analytics#56]
This is likely a very minor issue. I noticed that our analytics dashboard is advertising a mint rate on DAI of $1.0001 while our DApp is showing $1.0000. This may be a rounding difference between the two, but I'm more interested in confirming that the mint rate should never be greater than 1. I usually see numbers starting with a 0.9 on the mint side. I think our current intention is to never mint more than 1 OUSD for a given stablecoin.

<img width="570" alt="Screen Shot 2021-01-24 at 1 48 01 PM" src="https://user-images.githubusercontent.com/273937/105644643-709fa180-5e4b-11eb-8f7d-26f1902a6e48.png">

**Comment by DanielVF** [comment]
The analytics page is currently showing what the oracle is reporting the mint rate is, as opposed the actual mint rate used by the vault. (The vault applies the final 1-1 protection.)

I can definitely see how this is confusing, and am open to suggestions.

**Comment by micahalcorn** [comment]
@DanielVF makes sense, I think I'll just close this one.
