### ISSUE TITLE
Add monitoring to the latest contracts deployed to Mainnet

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/ousd-analytics#6]
Deployed:
- Governor: 0x8e7bDFeCd1164C46ad51b58e49A611F954D23377
- SingleAssetStaking: 0x501804B374EF06fa9C427476147ac09F1551B9A0
- OUSD: 0x2A8e1E676Ec238d8A992307B495b45B3fEAa5e86
- Multi-sig (5 signers): 0xe011fA2a6Df98c69383457d87a056Ed0103aA352
- Multi-sig (2 signers): 0xF14BBdf064E3F67f51cd9BD646aE3716aD938FDC

To be re-deployed and will have new addresses:

- Vault
- CompoundStrategy
- CurveStrategy
- AaveStrategy
- MixOracle

To be deployed:
- CompensationClaim

**Comment by mikeshultz** [comment]
oops

**Comment by mikeshultz** [comment]
I'm planning to do a general review of staking and integrate that starting today.  And we're already doing things with OUSD. 

As for the rest, any specific requests here?  The others would be new, but what do you want to know about them?  You just want logs stored for them?  Did you want some kind of notifications for some of these?

**Comment by franckc** [comment]
A few random thoughts:
 - In general it would be good to get a notification anytime something "admin related" happens. For example:
    - Any [Governor](https://github.com/OriginProtocol/origin-dollar/blob/master/contracts/contracts/governance/Governor.sol) event
   - Any event issued from a [VaultAdmin](https://github.com/OriginProtocol/origin-dollar/blob/master/contracts/contracts/vault/VaultAdmin.sol)

**Comment by mikeshultz** [comment]
@franckc since you submitted this, could you answer my questions?  I'm not really sure what this issue is looking for, or if it's just general notice.

Your admin/governor stuff in general (proxy contracts) would probably fit well in their own issue.

**Comment by franckc** [comment]
Let me dump my raw thoughts here and then we can discuss and break it up into separate GH issues.

In terms of monitoring, one idea would be to have 3 types severity for the events:
  1. **Info**. Normal user activity related. These are things like staking, minting, redeeming. Useful for our team to be aware of the general user activity. No action needed. This is informational only. Engineers don't really need to pay close attention to those.
  2. **Important**. Any change to a setting, to governance, etc.. These are important for the team to be aware of to understand the state of the system. The vast majority will be informational only. But rarely Either because they are not expected (ex: if we see a setting change and it was not initiated by anyone in our team, it is a security breach) or because we need to follow up (ex: Compound protocol changes or Oracle feed changes, etc...)
  3. **Urgent**. Needs immediate triage from the eng team. Security related or operational. For ex. OGN balance depleted on staking contract.
Then we could direct those events into 3 separate discord channels or email groups. Alternatively we could use a single channel but I'd be worried the "Info" events will cause too much noise and would cause us to miss Warning/High priority events.

In general I think it would be great to store in the DB all the logs for all contracts.

Here is my take on notifications:
 - Governor:
   - All [events](https://github.com/OriginProtocol/origin-dollar/blob/master/contracts/contracts/governance/Governor.sol#L34). Severity=Important
 - Vault
   - All events, except mint/redeem, from this [list](https://github.com/OriginProtocol/origin-dollar/blob/master/contracts/contracts/vault/VaultStorage.sol#L28). Severity=Important
   - Mint/Redeem events. Severity=Info. Except if the characteristics of the min/redeem are unusual. Then severity=Important
 - Strategies
   - All events from this [list](https://github.com/OriginProtocol/origin-dollar/blob/master/contracts/contracts/utils/InitializableAbstractStrategy.sol#L16). Severity=Important
 - Oracles
   - All events from this [list](https://github.com/OriginProtocol/origin-dollar/blob/master/contracts/contracts/oracle/MixOracle.sol#L15). Severity=Important
 - OUSD
   - Failed transactions (out of gas, reverts). Severity=Important
   - Unusual transactions (very large transfers, ...). Severity=Important

**Comment by mikeshultz** [comment]
Severity levels have already been implemented.  OUSD exceptional transactions have already been implemented.  Vault has been implemented.  Oracles are in progress, with Vault oracle price exceptions already done.

If you just want notifications for "all events" for the rest, that's fine, I guess.  I may decide to skip some if I think they'll cause too much noise(e.g. ERC20 Transfer events are not useful).  I thought this issue was started with a specific request in mind.

**Comment by mikeshultz** [comment]
Believe this has all been done, or at least moved to other issues(e.g. Aave strat).  CLosing
