### ISSUE TITLE
cToken numbers in DB appear to be invalid

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/ousd-analytics#79]
Looks like the `exchange_rate_stored` value being stored in the DB for cUSDT is invalid.  Off by many orders of magnitude.  Looks like the RPC function is returning correct numbers but what gets stored into the DB is wrong.  This is for both Postgres and SQLite, so probably ORM level.

EDIT: This may go beyond just the `exchange_rate_stored` for cUSDT.  Most of the other numbers also look wonky.

RPC data looks fine.  Here's some cUSDT calculations skipping the DB:

    >>> from core.blockchain.rpc import exchnageRateStored, totalSupply
    >>> exchange_rate = exchnageRateStored('0xf650c3d88d12db855b8bf7d11be6c55a4e07dcc9')
    >>> total_supply = totalSupply('0xf650c3d88d12db855b8bf7d11be6c55a4e07dcc9', 8)
    >>> total_supply * exchange_rate * Decimal(math.pow(10, 8 - 6))
    Decimal('198010098.9415288125005269222')

    >>> from core.blockchain.rpc import getCash, totalBorrows, totalReserves
    >>> cash = getCash('0xf650c3d88d12db855b8bf7d11be6c55a4e07dcc9', 6)
    >>> borrows = totalBorrows('0xf650c3d88d12db855b8bf7d11be6c55a4e07dcc9', 6)
    >>> reserves = totalReserves('0xf650c3d88d12db855b8bf7d11be6c55a4e07dcc9', 6)
    >>> cash + borrows - reserves
    Decimal('199010511.153774')

Should verify the numbers for all cTokens.

**Comment by mikeshultz** [comment]
I'm like 80% sure this is because it's late on a Friday and I've been looking at the wrong cToken (DAI instead of USDT)...  There probably isn't a problem here.  Will verify when I'm fresh...

**Comment by DanielVF** [comment]
Something must be wrong somewhere because I've still never gotten the math to work out with the numbers in the DB.

**Comment by mikeshultz** [comment]
Yeah, the numbers seem fine.  Here's a quick way to get the compound market value using two sets of vars:

    SELECT 
        block_number,
        total_cash + total_borrows - total_reserves AS col_a,
        total_supply * exchange_rate_stored * CASE WHEN address IN ('0x39aa39c021dfbae8fac545936693ac917d5e7563', '0xf650c3d88d12db855b8bf7d11be6c55a4e07dcc9') THEN power(10, 2) ELSE power(10, -10) END AS col_b 
    FROM core_ctokensnapshot
    WHERE block_number > 11753892
    ORDER BY address, block_number;

Numbers seem to check out with their dapp market page.  Closing.
