### ISSUE TITLE
OGN Staking Discrepancies

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/ousd-analytics#81]
@ZaHuPro  brought this up to me this morning. The OGN staking numbers reported by the two APIs don't jive.

http://analytics.ousd.com/api/v1/staking_stats_by_duration shows this:

    {"success": true, "data": [[30, 150761.832557], [90, 1865559.21467889], [365, 33392621.674489446]]}

http://analytics.ousd.com/api/v1/staking_stats shows this:

    {"success": true, "userCount": 391, "lockupSum": 35414582.433500335}

That's a difference of:

    >>> 35414582.433500335 - (150761.832557 + 1865559.21467889 + 33392621.674489446)
    5639.711774997413

**Comment by mikeshultz** [comment]
My local instance shows a different discrepancy....

    >>> 35409338.58596233 - (150761.832557 + 1864209.27785389 + 33394193.599008236)
    173.87654320895672

So that's cool.

**Comment by mikeshultz** [comment]
Comparing my local DB to prod was eye opening.  A lot of errors between the two.  Mostly invalid durations and rates.  According to my spot checks it looks like the backfill I was given had errors (prod) and the data that came from function call decoding (local) is accurate.

Kind of want to implement #33 to re-run this data...  

Though this might not even have to do with the original problem of numbers between the API calls lining up.  This was just to validate the data of the two DBs against eachother.  Will want reliable data before I can figure out which one is correct (if either).

**Comment by mikeshultz** [comment]
Adding some data pulled from my current local DB and prod.

[local-20210203.csv.txt](https://github.com/OriginProtocol/ousd-analytics/files/5922341/local-20210203.csv.txt)
[prod-20210203.csv.txt](https://github.com/OriginProtocol/ousd-analytics/files/5922342/prod-20210203.csv.txt)

**Comment by mikeshultz** [comment]
Fixing the one missing amount from #85, I now see a larger discrepancy on my local:

    >>> 35487095.92912534 - (150946.832557 + 1881264.30385389 + 33459964.763709236)
    -5079.970994785428

A change in the opposite direction as the one on prod.  aight...

**Comment by mikeshultz** [comment]
This seems to be confusion with this model and how it also represents withdraws.  Instead of marking previous stakes as no longer staked, another row is inserted into the core_ognstaked table and `is_staked` is set to `false`.

- There are 9 stakes with no rate data; withdraw events have no rate
- Also 9 where is_staked == false; is_staked is set to false on withdraw events

The query for one API is subtracting these withdraws from totals and the other is not.  

 `/api/v1/staking_stats_by_duration` however, excludes unlocked stakes but ignores withdraws entirely.  So there may be some unlocked stakes that have not been withdrawn inflating the number on `/api/v1/staking_stats`.

I'm not really sure how these endpoints are used so I'm not entirely sure which is accurate for its use.  Will need to find out.

**Comment by mikeshultz** [comment]
They're used by this: https://www.originprotocol.com/en/dashboard

The main question right now is, should "staked" data include unlocked tokens that have not yet been withdrawn, which I believe is the source of the discrepancy (that doesn't involve bad duration and rate data).

**Comment by mikeshultz** [comment]
According to @micahalcorn this data should include matured but not yet withdrawn stakes.  So we should be summing stakes and subtracting withdraws without regard to the unlock window (or any time factor, really).  

Will need to update the calculation for the duration bucket endpoint and the CoinGecko pools endpoint.

**Comment by mikeshultz** [comment]
It might actually not be possible to do this math.  Since there's no direct correlation between a withdraw event and a specific stake, we're left to try and infer.  A `Withdrawn` event can actually correlate to multiple stakes!

So, the overall sums from `/api/v1/staking_stats` does general math per use  and assumes the result is the amount currently staked for that user.  However, if we try and factor in durations, we can't really know that a withdraw affects that specific duration.  As an example for a single user:

Stake A: 100 OGN (90 days)
Stake B: 100 OGN (30 days)
Stake C: 100 OGN (365 days)
Withdraw A: 200 OGN

We have no idea if that withdraw includes A + B or B + C.  We can try and infer with date ranges, but I think that actually turns into a lot of work to do in the aggregate...  Will experiment but the best option might to be not to include matured but not withdrawn stakes.

**Comment by micahalcorn** [comment]
> A `Withdrawn` event can actually correlate to multiple stakes!

This was intentional. It's not that important that the sum include unlocked amounts.

Is it not as simple as just looking at the current balance of the staking contract though?

**Comment by mikeshultz** [comment]
> It's not that important that the sum include unlocked amounts.

okay... well, I'm a few hours deep into this already.  Let me see if I can finish it up or hit a wall before I scrap it.

> Is it not as simple as just looking at the current balance of the staking contract though?

No?  The problem I'm wrestling with is getting aggregate amounts for each duration.  Relatively easy to do going by the maturity date, but not by withdraws because it's hard to match them with stakes, especially with the current data schema.

Working on a running total process right now that whenever it hits a withdraw does a "look back" for that user and tries to verify the withdraw matches with their previous balance, then cancels them out and continues with the running total.

**Comment by mikeshultz** [comment]
Well, that was a lot more complex than I wanted it to be but think I have a solution for this finally.  Numbers check out.  Will likely roll this out this afternoon.

**Comment by mikeshultz** [comment]
Will deploy this later (probably tomorrow) when I can pay attention.
